server:
  port: 8913

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pes_db?useSSL=false&setUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: Pes_123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:static/

upload:
  dir: "./uploads/"

template:
  dir: "./templates/"

output:
  dir: "./outputs/"